### ISSUE TITLE
Provide a script to pass along to steam launch arguments

### ISSUE THREAD

**Issue by anthr76** [EnderIce2/rpc-bridge#2]
Similar to https://github.com/0e4ef622/wine-discord-ipc-bridge/blob/master/winediscordipcbridge-steam.sh I'd be curious if it's possible to instead use a script to invoke this project instead of installing a service through wine.

**Comment by EnderIce2** [comment]
Yes, you can use `winediscordipcbridge-steam.sh` from that project. Follow the instructions provided in that project and replace `BRIDGE="$BRIDGE_PATH/winediscordipcbridge.exe"` with `BRIDGE="$BRIDGE_PATH/bridge.exe"`. It should work as expected. I'll update this project to automatically close itself after the game exits, so it won't hang after the game closes.
