### ISSUE TITLE
Weird behaviour when using Proton-GE

### ISSUE THREAD

**Issue by Flowcheer** [EnderIce2/rpc-bridge#5]
The bridge works, but theres some oddities like lowercase names when using proton ge, and games that just show the exe name on discord
![image](https://github.com/user-attachments/assets/44a22f2e-1e77-46da-81f7-39b05be2b6ff)
im aware that unity games have some issues but in games like among us the bridge works fine with proton experimental
![image](https://github.com/user-attachments/assets/30c7d208-c449-4f94-9d15-36f03485ae08)

**Comment by EnderIce2** [comment]
Hmm, for me the RPC works without issues on GE-Proton9-12.

![image](https://github.com/user-attachments/assets/fa38a5fe-138f-43b8-b5e7-1339b26de948)
