### ISSUE TITLE
is it work in whisky?

### ISSUE THREAD

**Issue by Keinin04** [EnderIce2/rpc-bridge#6]

**Comment by EnderIce2** [comment]
It should work, check the [docs](https://enderice2.github.io/rpc-bridge/installation.html#macos) about macOS.

**Comment by amisukarei** [comment]
I am trying to get it to work with Whisky but I can't get it to work

**Comment by EnderIce2** [comment]
Hmm, I can't really help you because I don't have a MacBook... I reopened #1
