### ISSUE TITLE
rpc not working for certain game(s) despite working with other(s)

### ISSUE THREAD

**Issue by pparmy** [EnderIce2/rpc-bridge#7]
i spent ages trying to get rpc-bridge to work, only to find out that it was the game, webfishing, that wasnt showing the rpc
i tested ultrakill, and sure enough, it works just fine - but webfishing doesn't
im on steamos (steamdeck)
[bridge.log](https://github.com/user-attachments/files/17563485/bridge.log)

**Comment by EnderIce2** [comment]
The log file you attached is corrupted; I resolved it in [this artifact](https://github.com/EnderIce2/rpc-bridge/actions/runs/11583904821/artifacts/2120475211).

Based on your description, it seems likely that the RPC library used by WEBFISHING (I guess you are talking about [this one](https://store.steampowered.com/app/3146520/WEBFISHING/)) may differ in some way, possibly related to #4.

**Comment by EnderIce2** [comment]
> and wiped the proton files for a fresh start

Everything under `pfx` directory? Because `system.reg` contains the service config and keeps the `Install` button greyed out.

> upon launching the exe via protontricks

Did you install it through protontricks? If so, try setting it up using the [Launch Options](https://enderice2.github.io/rpc-bridge/installation.html#using-bridgesh) instead.

**Comment by EnderIce2** [comment]
> where is system.reg?

It’s located in the `pfx` directory.

> when i do that, there is no option to install it as it appears as the script doesn’t start. or it’s at least in the background

Using Launch Options, it silently starts in the background on the specified game.
For example, with Among Us, I use these Launch Options:
`/home/enderice2/rpc-bridge/build/bridge.sh obs-gamecapture gamemoderun %command%`

**Comment by EnderIce2** [comment]
> it’s working now after wiping the directory and not messing with protontricks. or i think that’s why it’s not stopped like last time.?

It’s possible something may have been broken.
I recommend using Launch Options next time, it's easier and more thoroughly tested.

> is there anything we can do about linking the RPC library (if that’s how it works) for webfishing? or is that someone else’s issue to fix

I tested the game myself and it doesn't have Discord integration. That's up to the game developer to add it.

- Let me know if you have any other issues.
